# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 017782be0f716d45859daa3860c77bb22f10392024e81e6a23db65bc55bd3e36fba8e26d150b4576e494d608d5ee1bef9ff4c949e6f9fe402ce2ba1ea375963e

test:
  secret_key_base: 6d1fb727f07920ba81bb5aad35323c34e0ec50ca6f4d3d7b9d9e10b734af10734074873fcb29e7aafab925b1d183ab3f2d58a62c3447f9830ada17cd340b1259

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
